/**
 * DNS 配置生成器
 */

import type { DNSConfig } from "@subboost/core/types/config";

export const DEFAULT_DNS_CONFIG: DNSConfig = {
  enable: true,
  listen: "127.0.0.1:5335",
  "respect-rules": true,
  "enhanced-mode": "fake-ip",
  "fake-ip-range": "198.18.0.1/16",
  "use-system-hosts": false,
  "default-nameserver": ["223.5.5.5", "119.29.29.29"],
  nameserver: [
    "https://dns.alidns.com/dns-query#DIRECT",
    "https://doh.pub/dns-query#DIRECT",
  ],
  "proxy-server-nameserver": [
    "https://dns.alidns.com/dns-query#DIRECT",
    "https://doh.pub/dns-query#DIRECT",
  ],
  fallback: [
    "https://1.1.1.1/dns-query#RULES",
    "https://8.8.8.8/dns-query#RULES",
  ],
  "fallback-lazy-query": true,
  "fallback-filter": {
    geoip: true,
    "geoip-code": "CN",
    ipcidr: ["240.0.0.0/4", "0.0.0.0/32", "127.0.0.1/32"],
    domain: [
      "+.google.com",
      "+.facebook.com",
      "+.twitter.com",
      "+.youtube.com",
      "+.xn--ngstr-lra8j.com",
      "+.google.cn",
      "+.googleapis.cn",
      "+.googleapis.com",
      "+.gvt1.com",
    ],
  },
  // Google Play 下载 CDN 与 YouTube 视频 CDN 在国内常被 DNS 污染到国内 IP，
  // 直接指定国际 DoH 解析，避免被 geoip:cn 规则截胡导致下载失败
  "nameserver-policy": {
    "+.gvt1.com": ["https://1.1.1.1/dns-query#RULES", "https://8.8.8.8/dns-query#RULES"],
    "+.gvt2.com": ["https://1.1.1.1/dns-query#RULES", "https://8.8.8.8/dns-query#RULES"],
    "+.gvt3.com": ["https://1.1.1.1/dns-query#RULES", "https://8.8.8.8/dns-query#RULES"],
    "+.googlevideo.com": ["https://1.1.1.1/dns-query#RULES", "https://8.8.8.8/dns-query#RULES"],
    "+.ggpht.com": ["https://1.1.1.1/dns-query#RULES", "https://8.8.8.8/dns-query#RULES"],
    "+.googleusercontent.com": ["https://1.1.1.1/dns-query#RULES", "https://8.8.8.8/dns-query#RULES"],
    "+.googleapis.com": ["https://1.1.1.1/dns-query#RULES", "https://8.8.8.8/dns-query#RULES"],
    "+.gstatic.com": ["https://1.1.1.1/dns-query#RULES", "https://8.8.8.8/dns-query#RULES"],
  },
  "fake-ip-filter": [
    "*.lan",
    "stun.*.*.*",
    "stun.*.*",
    "time.windows.com",
    "time.nist.gov",
    "time.apple.com",
    "time.asia.apple.com",
    "*.ntp.org.cn",
    "*.openwrt.pool.ntp.org",
    "time1.cloud.tencent.com",
    "time.ustc.edu.cn",
    "pool.ntp.org",
    "ntp.ubuntu.com",
    "ntp.aliyun.com",
    "ntp1.aliyun.com",
    "ntp2.aliyun.com",
    "ntp3.aliyun.com",
    "ntp4.aliyun.com",
    "ntp5.aliyun.com",
    "ntp6.aliyun.com",
    "ntp7.aliyun.com",
    "time1.aliyun.com",
    "time2.aliyun.com",
    "time3.aliyun.com",
    "time4.aliyun.com",
    "time5.aliyun.com",
    "time6.aliyun.com",
    "time7.aliyun.com",
    "*.time.edu.cn",
    "time1.apple.com",
    "time2.apple.com",
    "time3.apple.com",
    "time4.apple.com",
    "time5.apple.com",
    "time6.apple.com",
    "time7.apple.com",
    "time1.google.com",
    "time2.google.com",
    "time3.google.com",
    "time4.google.com",
    "music.163.com",
    "*.music.163.com",
    "*.126.net",
    "musicapi.taihe.com",
    "music.taihe.com",
    "songsearch.kugou.com",
    "trackercdn.kugou.com",
    "*.kuwo.cn",
    "api-jooxtt.sanook.com",
    "api.joox.com",
    "joox.com",
    "y.qq.com",
    "*.y.qq.com",
    "streamoc.music.tc.qq.com",
    "mobileoc.music.tc.qq.com",
    "isure.stream.qqmusic.qq.com",
    "dl.stream.qqmusic.qq.com",
    "aqqmusic.tc.qq.com",
    "amobile.music.tc.qq.com",
    "*.xiami.com",
    "*.music.migu.cn",
    "music.migu.cn",
    "*.msftconnecttest.com",
    "*.msftncsi.com",
    "localhost.ptlogin2.qq.com",
    "*.*.*.srv.nintendo.net",
    "*.*.stun.playstation.net",
    "xbox.*.*.microsoft.com",
    "*.ipv6.microsoft.com",
    "*.*.xboxlive.com",
    "speedtest.cros.wr.pvp.net",
  ],
};
